// Code generated by generate_domain_models.go.
// This file is generated from the sqlc models.go file for developers convinience.
// Check the sqlc models.go file for the source of truth.

package models

import (
	"time"
	"github.com/google/uuid"
)

// Action represents the domain model for Action
type Action struct {
	ID uuid.UUID `json:"id"`
	LeakID uuid.UUID `json:"leak_id"`
	ActionType ActionTypeEnum `json:"action_type"`
	Status ActionStatusEnum `json:"status"`
	Result ActionResultEnum `json:"result"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateActionParams represents parameters for creating a Action
type CreateActionParams struct {
	LeakID uuid.UUID `json:"leak_id"`
	ActionType ActionTypeEnum `json:"action_type"`
	Status ActionStatusEnum `json:"status"`
	Result ActionResultEnum `json:"result"`
}

// UpdateActionParams represents parameters for updating a Action
type UpdateActionParams struct {
	ID uuid.UUID `json:"id"` // Primary key
	LeakID *uuid.UUID `json:"leak_id"`
	ActionType *NullActionTypeEnum `json:"action_type"`
	Status *NullActionStatusEnum `json:"status"`
	Result *ActionResultEnum `json:"result"`
}

// GetActionByIDRow represents query-specific parameters/results for action operations
// This struct is auto-generated from sqlc queries and should be reviewed before using
type GetActionByIDRow struct {
	ID uuid.UUID `json:"id"`
	LeakID uuid.UUID `json:"leak_id"`
	ActionType NullActionTypeEnum `json:"action_type"`
	Status NullActionStatusEnum `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
