// Code generated by generate_domain_models.go.
// In case of editing this file please make sure of consistency
// If you have to change the template, please update the template in the scripts/generate_domain_models.go file.

package models

// Domain enum types copied from sqlc models

type ActionResultEnum string

const (
	ActionResultEnumSuccess ActionResultEnum = "success"
	ActionResultEnumFailure ActionResultEnum = "failure"
	ActionResultEnumPending ActionResultEnum = "pending"
	ActionResultEnumOther   ActionResultEnum = "other"
)

type ActionStatusEnum string

const (
	ActionStatusEnumPending  ActionStatusEnum = "pending"
	ActionStatusEnumApproved ActionStatusEnum = "approved"
	ActionStatusEnumModified ActionStatusEnum = "modified"
	ActionStatusEnumDenied   ActionStatusEnum = "denied"
)

type ActionTypeEnum string

const (
	ActionTypeEnumRetryPayment ActionTypeEnum = "retry_payment"
	ActionTypeEnumOutreach     ActionTypeEnum = "outreach"
	ActionTypeEnumLinearTask   ActionTypeEnum = "linear_task"
	ActionTypeEnumEmail        ActionTypeEnum = "email"
	ActionTypeEnumOther        ActionTypeEnum = "other"
)

type EventStatusEnum string

const (
	EventStatusEnumPending   EventStatusEnum = "pending"
	EventStatusEnumProcessed EventStatusEnum = "processed"
	EventStatusEnumFailed    EventStatusEnum = "failed"
)

type EventTypeEnum string

const (
	EventTypeEnumPaymentFailed    EventTypeEnum = "payment_failed"
	EventTypeEnumPaymentSucceeded EventTypeEnum = "payment_succeeded"
	EventTypeEnumPaymentRefunded  EventTypeEnum = "payment_refunded"
	EventTypeEnumPaymentUpdated   EventTypeEnum = "payment_updated"
)

type LeakTypeEnum string

const (
	LeakTypeEnumFailedPayments       LeakTypeEnum = "failed_payments"
	LeakTypeEnumUnbilledUsage        LeakTypeEnum = "unbilled_usage"
	LeakTypeEnumQuietChurn           LeakTypeEnum = "quiet_churn"
	LeakTypeEnumCouponDiscountMisuse LeakTypeEnum = "coupon_discount_misuse"
	LeakTypeEnumTrialForever         LeakTypeEnum = "trial_forever"
	LeakTypeEnumOther                LeakTypeEnum = "other"
)

type PaymentStatusEnum string

const (
	PaymentStatusEnumPending   PaymentStatusEnum = "pending"
	PaymentStatusEnumSucceeded PaymentStatusEnum = "succeeded"
	PaymentStatusEnumFailed    PaymentStatusEnum = "failed"
	PaymentStatusEnumOther     PaymentStatusEnum = "other"
)

type PaymentTypeEnum string

const (
	PaymentTypeEnumWebhook PaymentTypeEnum = "webhook"
	PaymentTypeEnumHistory PaymentTypeEnum = "history"
)

type NullActionTypeEnum struct {
	ActionTypeEnum ActionTypeEnum `json:"action_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if ActionTypeEnum is not NULL
}

type NullActionResultEnum struct {
	ActionResultEnum ActionResultEnum `json:"action_result_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ActionResultEnum is not NULL
}

type NullActionStatusEnum struct {
	ActionStatusEnum ActionStatusEnum `json:"action_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ActionStatusEnum is not NULL
}

type NullEventTypeEnum struct {
	EventTypeEnum EventTypeEnum `json:"event_type_enum"`
	Valid         bool          `json:"valid"` // Valid is true if EventTypeEnum is not NULL
}

type NullEventStatusEnum struct {
	EventStatusEnum EventStatusEnum `json:"event_status_enum"`
	Valid           bool            `json:"valid"` // Valid is true if EventStatusEnum is not NULL
}
