// Code generated by generate_domain_models.go.
// This file is generated from the sqlc models.go file for developers convinience.
// Check the sqlc models.go file for the source of truth.

package models

import (
	"time"
	"github.com/google/uuid"
)

// Event represents the domain model for Event
type Event struct {
	ID uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	ProviderID uuid.UUID `json:"provider_id"`
	EventType EventTypeEnum `json:"event_type"`
	EventID string `json:"event_id"`
	Status EventStatusEnum `json:"status"`
	Data interface{} `json:"data"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateEventParams represents parameters for creating a Event
type CreateEventParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ProviderID uuid.UUID `json:"provider_id"`
	EventType EventTypeEnum `json:"event_type"`
	EventID string `json:"event_id"`
	Status EventStatusEnum `json:"status"`
	Data interface{} `json:"data"`
}

// UpdateEventParams represents parameters for updating a Event
type UpdateEventParams struct {
	TenantID   uuid.UUID         `json:"tenant_id"`
	ProviderID uuid.UUID         `json:"provider_id"`
	EventType  NullEventTypeEnum   `json:"event_type"`
	EventID    *string             `json:"event_id"`
	Status     NullEventStatusEnum `json:"status"`
	Data       interface{}              `json:"data"`
	ID         uuid.UUID         `json:"id"`
}
