// Code generated by generate_domain_models.go.
// This file is generated from the sqlc models.go file for developers convinience.
// Check the sqlc models.go file for the source of truth.

package models

import (
	"time"

	"github.com/google/uuid"
)

// Provider represents the domain model for Provider
type Provider struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateProviderParams represents parameters for creating a Provider
type CreateProviderParams struct {
	Name string `json:"name"`
}

// UpdateProviderParams represents parameters for updating a Provider
type UpdateProviderParams struct {
	ID   uuid.UUID `json:"id"` // Primary key
	Name *string   `json:"name"`
}
