// Code generated by generate_domain_models.go.
// This file is generated from the sqlc models.go file for developers convinience.
// Check the sqlc models.go file for the source of truth.

package models

import (
	"time"
	"github.com/google/uuid"
)

// Tenant represents the domain model for Tenant
type Tenant struct {
	ID uuid.UUID `json:"id"`
	Email string `json:"email"`
	Name string `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateTenantParams represents parameters for creating a Tenant
type CreateTenantParams struct {
	Email string `json:"email"`
	Name string `json:"name"`
}

// UpdateTenantParams represents parameters for updating a Tenant
type UpdateTenantParams struct {
	ID uuid.UUID `json:"id"` // Primary key
	Email *string `json:"email"`
	Name *string `json:"name"`
}
