// Code generated by generate_domain_models.go.
// This file is generated from the sqlc models.go file for developers convinience.
// Check the sqlc models.go and *.sql.go files for the source of truth.

package models

import (
	"time"

	"github.com/google/uuid"
)

// User represents the domain model for User
type User struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
	ExternalID *string   `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CreateUserParams struct {
	Email      string  `json:"email"`
	Name       string  `json:"name"`
	ExternalID *string `json:"external_id"`
}

type UpdateUserParams struct {
	ID         uuid.UUID `json:"id"`
	Email      *string   `json:"email"`
	Name       *string   `json:"name"`
	ExternalID *string   `json:"external_id"`
}
