version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: revenue-leak-postgres
    environment:
      POSTGRES_DB: revenue_leak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - revenue-leak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: revenue-leak-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - revenue-leak-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  revenue-leak-network:
    driver: bridge