// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAction = `-- name: CreateAction :one
INSERT INTO actions (leak_id, action_type, status, result) VALUES ($1, $2, $3, $4) RETURNING id, leak_id, action_type, status, result, created_at, updated_at
`

type CreateActionParams struct {
	LeakID     pgtype.UUID      `json:"leak_id"`
	ActionType ActionTypeEnum   `json:"action_type"`
	Status     ActionStatusEnum `json:"status"`
	Result     ActionResultEnum `json:"result"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, createAction,
		arg.LeakID,
		arg.ActionType,
		arg.Status,
		arg.Result,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.LeakID,
		&i.ActionType,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAction = `-- name: DeleteAction :execrows
DELETE FROM actions WHERE id = $1
`

func (q *Queries) DeleteAction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActionByIDForTenant = `-- name: GetActionByIDForTenant :one
SELECT a.id, a.leak_id, a.action_type, a.status, a.result, a.created_at, a.updated_at
FROM actions a
JOIN leaks l ON l.id = a.leak_id
WHERE a.id = $1 AND l.tenant_id = $2
`

type GetActionByIDForTenantParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetActionByIDForTenant(ctx context.Context, arg GetActionByIDForTenantParams) (Action, error) {
	row := q.db.QueryRow(ctx, getActionByIDForTenant, arg.ID, arg.TenantID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.LeakID,
		&i.ActionType,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllActionsForTenant = `-- name: GetAllActionsForTenant :many
SELECT a.id, a.leak_id, a.action_type, a.status, a.result, a.created_at, a.updated_at
FROM actions a
JOIN leaks l ON l.id = a.leak_id
WHERE l.tenant_id = $1
`

func (q *Queries) GetAllActionsForTenant(ctx context.Context, tenantID pgtype.UUID) ([]Action, error) {
	rows, err := q.db.Query(ctx, getAllActionsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.LeakID,
			&i.ActionType,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAction = `-- name: UpdateAction :one
UPDATE actions 
SET 
    leak_id = CASE WHEN $2::uuid IS NOT NULL THEN $2::uuid ELSE leak_id END, 
    action_type = CASE WHEN $3::action_type_enum IS NOT NULL THEN $3::action_type_enum ELSE action_type END, 
    status = CASE WHEN $4::action_status_enum IS NOT NULL THEN $4::action_status_enum ELSE status END, 
    result = CASE WHEN $5::action_result_enum IS NOT NULL THEN $5::action_result_enum ELSE result END 
WHERE id = $1 
RETURNING id, leak_id, action_type, status, result, created_at, updated_at
`

type UpdateActionParams struct {
	ID         pgtype.UUID          `json:"id"`
	LeakID     pgtype.UUID          `json:"leak_id"`
	ActionType NullActionTypeEnum   `json:"action_type"`
	Status     NullActionStatusEnum `json:"status"`
	Result     NullActionResultEnum `json:"result"`
}

func (q *Queries) UpdateAction(ctx context.Context, arg UpdateActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, updateAction,
		arg.ID,
		arg.LeakID,
		arg.ActionType,
		arg.Status,
		arg.Result,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.LeakID,
		&i.ActionType,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
