// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllEvents(ctx context.Context) (int64, error)
	CreateAction(ctx context.Context, arg CreateActionParams) (Action, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAction(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteEvent(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	GetActionByIDForTenant(ctx context.Context, arg GetActionByIDForTenantParams) (Action, error)
	GetAllActionsForTenant(ctx context.Context, tenantID pgtype.UUID) ([]Action, error)
	GetAllEvents(ctx context.Context) ([]Event, error)
	GetAllEventsPaginated(ctx context.Context, arg GetAllEventsPaginatedParams) ([]Event, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateAction(ctx context.Context, arg UpdateActionParams) (Action, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
