// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAction(ctx context.Context, arg CreateActionParams) (Action, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAction(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteEvent(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	// actions table queries
	GetActionByIDForTenant(ctx context.Context, arg GetActionByIDForTenantParams) (Action, error)
	GetAllActionsForTenant(ctx context.Context, tenantID pgtype.UUID) ([]Action, error)
	GetAllEventsForTenant(ctx context.Context, tenantID pgtype.UUID) ([]Event, error)
	GetAllUsersForTenant(ctx context.Context, tenantID pgtype.UUID) ([]User, error)
	// events table queries
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	// users table queries
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error)
	UpdateAction(ctx context.Context, arg UpdateActionParams) (Action, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
