run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - rdl-api
            - github.com/stretchr/testify
    revive:
      severity: error
      rules:
        - name: unused-parameter
          severity: warning
          disabled: false
          exclude: [""]
          - name: unused-parameter
            severity: warning
            disabled: false
            exclude: [""]
            arguments:
              - allow-regex: "^(_|r)$"         
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - shadow
    misspell:
      locale: US

  enable:
    - revive  # replaces golint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck
    - bodyclose
    - gosec
    - unconvert
    - unparam
  disable:
    - err113  # too strict for error wrapping
    - depguard  # disabled due to configuration issues with local imports

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
